### ISSUE TITLE
Persistent Auth State

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#127]
## Basic Information
Currently when a logged in user refreshes the page, the state is gone.
- Change the store from user.js to auth.js (Update everywhere its used)
- Use auth.js to store the data from what returns from firebase auth

This might be a good start:
https://firebase.google.com/docs/auth/web/auth-state-persistence

**Comment by ChantelleKerr** [comment]
This could also be helpful https://nuxt.com/modules/pinia-plugin-persistedstate
@orange-my-cat @22260513

**Comment by nicodeas** [comment]
could be helpful, https://vueuse.org/firebase/useAuth/
