### ISSUE TITLE
Install Pinia

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#17]
## Basic Information
Pinia is a state management tool that allows us to share states across multiple components where needed.

**Comment by ashtonicci** [comment]
@ChantelleKerr 

Hi, can I raise an MR for this?

**Comment by ChantelleKerr** [comment]
> @ChantelleKerr
> 
> Hi, can I raise an PR for this?

Go for it :)

**Comment by ashtonicci** [comment]
> 

Having an issue pushing my changes

`git push --set-upstream origin feature/issue-17-install-pinia
remote: Permission to codersforcauses/wadl.git denied to ashtonicci.
fatal: unable to access 'https://github.com/codersforcauses/wadl.git/': The requested URL returned error: 403`

**Comment by GlendleNguyen** [comment]
That's an interesting issue! Maybe something to do with your credentials? Have a look at the following discussion: 
https://stackoverflow.com/questions/47465644/github-remote-permission-denied

**Comment by ashtonicci** [comment]
Hi Glen!, 

Thanks for the reply, set up with SSH now but the issue still persists, wonder if its an issue more on the project-side? Do I need to be added to a group or something in order to push my branch? 

Thanks

**Comment by ChantelleKerr** [comment]
> Hi Glen!,
> 
> Thanks for the reply, set up with SSH now but the issue still persists, wonder if its an issue more on the project-side? Do I need to be added to a group or something in order to push my branch?
> 
> Thanks

Have you forked the repo? You wont have permission to clone to repo and push, as only project members can do that.

**Comment by ashtonicci** [comment]
Oops! That was it, thanks, just raised a PR :)
