### ISSUE TITLE
Change Dropdown Component

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#189]
## Basic Information
Currently we are using the default select tag.
Make it match the rest of our dropdown components (SearchSelect & MultiSelect)

**Comment by KKatariah** [comment]
Unfortunately the browser controls the styling of <option> elements so we would have to rewrite the dropdown in a different way to style it.

**Comment by ChantelleKerr** [comment]
> Unfortunately the browser controls the styling of elements so we would have to rewrite the dropdown in a different way to style it.

Are you still planning to work on this? You'd have to create your own component (It would be somewhat similar to the SearchSelect and MultiSelect) It's good practicing making components :)
