### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by cjnbennett** [codersforcauses/wadl#19]
## Basic Information
* Create database schema

**Comment by benvarian** [comment]
https://lucid.app/lucidchart/9afe89f3-514a-4c8b-b706-066deff17d11/edit?viewport_loc=-251%2C95%2C2673%2C1373%2C0_0&invitationId=inv_5cec4527-281b-41b2-a721-b104d1ce1c76

**Comment by benvarian** [comment]
https://lucid.app/lucidchart/9afe89f3-514a-4c8b-b706-066deff17d11/edit?viewport_loc=-251%2C95%2C2673%2C1373%2C0_0&invitationId=inv_5cec4527-281b-41b2-a721-b104d1ce1c76
