### ISSUE TITLE
Initialise Firebase App 

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#21]
## Basic Information
- Setup firebase config
- Make sure all key-values are stored in a .env file
- Setup up a .env-template file with only the keys displayed (this should be added to github)

**Comment by rabbanirizwan** [comment]
@ChantelleKerr I wanted to work on this

but I will need keys for that

**Comment by ChantelleKerr** [comment]
> @ChantelleKerr I wanted to work on this
> 
> but I will need keys for that

Hey, unfortunately the keys are only available for our project members
