### ISSUE TITLE
View tournament registered teams

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#237]
## Prerequisite
#172 - Manage Tournament Page, this page must have dynamic routing set up with the correct tournament ID passed to the page

## Basic Information
When teams is clicked: 
<img width="102" alt="Screen Shot 2023-02-02 at 7 02 39 pm" src="https://user-images.githubusercontent.com/45170409/216307755-9b08b7ad-3b6a-4fce-b7ae-dd48314a6003.png">
- Opens up a modal
- gets teams by `tournament_id` where the level is the level that is clicked on (in this case junior)
- Displays a list of teams in that level - list to become scrollable if too many
<img width="484" alt="Screen Shot 2023-02-02 at 7 02 33 pm" src="https://user-images.githubusercontent.com/45170409/216307761-12e25551-2bc9-4884-9c04-0a0271bd408c.png">

**Comment by ChantelleKerr** [comment]
Manage tournaments and the updated tournament dummy data is now in the development branch @LemonTheSour 
Please note that theres no longer team ids in the tournament structure so you'll have to query the teams document by tournament id and level from the teams pinia store.
Let me know if you need help :D

**Comment by rezbyte** [comment]
May I help out with this issue @LemonTheSour?

**Comment by LemonTheSour** [comment]
If you need it done sooner than I'm doing it, help yourself ^^ Don't wanna gum up anyone else's issues
