### ISSUE TITLE
Research how to handle sign up requests

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#29]
## Basic Information
- Anyone can sign up however the super admin has the option to accept or reject the request. 
- Accepted users should be able to sign in straight away, and rejected or 'waiting for approval' requests cannot.
- Research how firebase can handle this.
- Design schema with this feature in mind. 

Post any relevant links or information here.

**Comment by benvarian** [comment]
https://docs.google.com/document/d/1Kz1bxbh2WgqaLC5yTWS3SWhBTgKChS0fWwG9LlI5gqA/edit?usp=sharing

**Comment by ChantelleKerr** [comment]
Closing because it's been researched. Good job!!
