### ISSUE TITLE
Add validation to Registration Form

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#89]
## Basic Information
- Passwords must match
- Email must be a valid email
- Display an error message on the fields that are invalid

**Comment by gauravsahu21** [comment]
@ChantelleKerr can you assign this issue to me I would like to work on this.

**Comment by ChantelleKerr** [comment]
> gauravsahu21

Hi, one of our project members has already been assigned to this issue. We would prefer our project members to take on this issue before anyone outside our team.
